Ticket7589 install script fix adding autostart link
ISISComputingGroup/ibex_utils pull request #153
Opened 2023-02-22 15:37 UTC by pheest

If the autostart is in the 'all users' folder, it is removed from there.
If the spudulike user doesn't exist yet, it is created and file copied.
If the spudulike user exists, but the autostart isn't present there, it is copied in.
If the autostart is already where it should be, does nothing.

2023-02-23 12:41 UTC, FreddieAkeroyd commented
We will probably need to separate the creation of spudulike out from the link creation a bit more, we don't want the account accidentally created on a developer computer testing an install. Also we have a few special cases like the engfin stress computer that do not run under spudulike and so would not want one creating. Normally an install would be run under the account that will be running ibex, so making links for "current logged on user" would cover things. The special case is that if an install is being done as part of an instrument image build, in which case it would want links in spudulike which may not exist at that point.

2023-02-24 14:55 UTC, pheest commented
Added username verification on account creation.
If the user isn't 'Administrator', nothing is done.
So this can only happen in the special case of new computer install.

2023-03-17 13:38 UTC, NikolaRoev requested changes
The ibex system boot batch file is currently added to start up only for the `spudulike` account. As mentioned in https://github.com/ISISComputingGroup/ibex_utils/pull/153#issuecomment-1441706421 some machines might not be using that user name.
I think this needs to be examined more to see if this is accepted behaviour or if the batch file should be added for the current user, or if the user should be decided by some other means. Was there an issue with adding the batch file to the global startup folder?

I think creation of the `spudulike` user should be separated out into its own task if it's still relevant. Someone doing a new install might not want to create a new user without knowing in the "autostart" step, even if the situation might be quite rare.

Something to keep in mind, if it was not known, `os.getlogin` will return the account that started the terminal not the currently logged in one.

Please revert the change done in https://github.com/ISISComputingGroup/ibex_utils/pull/145.

2023-03-17 13:38 UTC, NikolaRoev commented on installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
> +
```suggestion

```
Removing white space should fix the no new line indicator.

2023-03-17 13:38 UTC, NikolaRoev commented on installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
> +            if (myname == "Administrator"):
```suggestion
            if myname == "Administrator":
```

2023-03-23 14:11 UTC, NikolaRoev requested changes
If there is an error during the execution of `create_spudulike.bat` through the Python code and the new terminal is closed manually the initial terminal will hang.

Even if there is a failure in `create_spudulike.bat` that is not reflected in the install script and execution continues as if the task was successful.

I would recommend doing everything that is currently done in the batch file in the Python code and through the `AdminCommandBuilder` class.

2023-03-29 13:20 UTC, NikolaRoev commented on installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
> +            admin_commands.add_command("xcopy", "/I " + from_path + " \"" + user_folder + "\"")
Why are we copying the startup file in the `Create spudulike user` step?

2023-05-02 14:35 UTC, Tom-Willemsen approved these changes

2023-05-02 14:36 UTC, merged